import json
from pathlib import Path

import numpy as np
import tensorflow as tf

from flask import Flask, jsonify, request
from flask_cors import CORS
from PIL import Image


# =====================================================
# Paths
# =====================================================

BASE_DIR = Path(__file__).resolve().parent

# =====================================================
# Crop Recognition Model
# =====================================================
#
# IMPORTANT:
# This is the new 49-class model generated by
# convert_model.py
#
# DO NOT use:
#   crop_model_fixed.keras
#
# DO NOT use:
#   crop_model.keras
#   if crop_model.keras is still the old model
#
# =====================================================

MODEL_PATH = BASE_DIR / "models" / "crop_model_49.keras"

LABELS_PATH = BASE_DIR / "labels.json"


# =====================================================
# Flask App
# =====================================================

app = Flask(__name__)


# =====================================================
# CORS
# =====================================================

CORS(
    app,
    resources={
        r"/predict": {
            "origins": [
                "http://localhost:5173",
            ]
        }
    },
)


# =====================================================
# Load Labels
# =====================================================

print("Loading crop labels...")

if not LABELS_PATH.exists():
    raise RuntimeError(
        f"Labels file not found at: {LABELS_PATH}"
    )

with open(
    LABELS_PATH,
    "r",
    encoding="utf-8",
) as file:
    labels = json.load(file)


print(f"Loaded {len(labels)} crop labels.")


# =====================================================
# Validate Labels
# =====================================================

if not isinstance(labels, list):
    raise RuntimeError(
        "labels.json must contain a JSON array."
    )


if len(labels) == 0:
    raise RuntimeError(
        "labels.json contains no crop labels."
    )


if len(set(labels)) != len(labels):
    raise RuntimeError(
        "labels.json contains duplicate crop labels."
    )


# =====================================================
# Load Model
# =====================================================

print("Loading crop recognition model...")


if not MODEL_PATH.exists():
    raise RuntimeError(
        f"Crop model not found at: {MODEL_PATH}"
    )


model = tf.keras.models.load_model(
    MODEL_PATH,
    compile=False,
)


print(
    "Crop recognition model loaded successfully."
)


# =====================================================
# Model Information
# =====================================================

print(
    "Input shape:",
    model.input_shape,
)

print(
    "Output shape:",
    model.output_shape,
)


# =====================================================
# Validate Model / Labels
# =====================================================

try:

    expected_classes = int(
        model.output_shape[-1]
    )

except (TypeError, ValueError):

    raise RuntimeError(
        "Unable to determine the number of "
        "output classes from the model."
    )


if expected_classes != len(labels):

    raise RuntimeError(
        f"Model outputs {expected_classes} classes, "
        f"but labels.json contains {len(labels)} labels."
    )


print(
    f"Model and labels successfully matched: "
    f"{expected_classes} classes."
)


# =====================================================
# Model Input Validation
# =====================================================

model_input_shape = model.input_shape


if len(model_input_shape) != 4:

    raise RuntimeError(
        "Expected model input shape like "
        "(None, height, width, channels), "
        f"but received {model_input_shape}"
    )


input_height = model_input_shape[1]
input_width = model_input_shape[2]
input_channels = model_input_shape[3]


if input_height is None or input_width is None:

    raise RuntimeError(
        "Model input height/width must be defined."
    )


if input_channels != 3:

    raise RuntimeError(
        f"Expected 3 input channels (RGB), "
        f"but model expects {input_channels}."
    )


print(
    f"Image input size: "
    f"{input_width} x "
    f"{input_height} x "
    f"{input_channels}"
)


# =====================================================
# Health Check
# =====================================================

@app.get("/")
def health_check():

    return jsonify(
        {
            "success": True,

            "message":
                "Hawkins Farm Crop Recognition API Running",

            "model_loaded":
                model is not None,

            "classes":
                len(labels),

            "input_size":
                {
                    "width":
                        input_width,

                    "height":
                        input_height,

                    "channels":
                        input_channels,
                },
        }
    )


# =====================================================
# Crop Prediction
# =====================================================

@app.post("/predict")
def predict_crop():

    # -------------------------------------------------
    # Validate Image
    # -------------------------------------------------

    if "image" not in request.files:

        return jsonify(
            {
                "success": False,
                "message": "No image uploaded.",
            }
        ), 400


    image_file = request.files["image"]


    if (
        not image_file
        or image_file.filename == ""
    ):

        return jsonify(
            {
                "success": False,
                "message": "Please select an image.",
            }
        ), 400


    try:

        # ---------------------------------------------
        # Open Image
        # ---------------------------------------------

        image = Image.open(image_file)


        # ---------------------------------------------
        # Convert To RGB
        # ---------------------------------------------

        image = image.convert("RGB")


        # ---------------------------------------------
        # Resize According To Model
        # ---------------------------------------------

        image = image.resize(
            (
                int(input_width),
                int(input_height),
            )
        )


        # ---------------------------------------------
        # Convert To NumPy
        # ---------------------------------------------

        image_array = np.asarray(
            image,
            dtype=np.float32,
        )


        # ---------------------------------------------
        # Validate Image Shape
        # ---------------------------------------------

        if image_array.shape != (
            int(input_height),
            int(input_width),
            3,
        ):

            return jsonify(
                {
                    "success": False,
                    "message":
                        "Invalid image dimensions.",
                }
            ), 400


        # ---------------------------------------------
        # Add Batch Dimension
        # ---------------------------------------------

        image_array = np.expand_dims(
            image_array,
            axis=0,
        )


        # ---------------------------------------------
        # Prediction
        #
        # IMPORTANT:
        #
        # The saved model is expected to contain
        # its own preprocessing/rescaling layer.
        #
        # Therefore we do NOT apply another
        # preprocessing function here.
        # ---------------------------------------------

        predictions = model.predict(
            image_array,
            verbose=0,
        )


        probabilities = predictions[0]


        # ---------------------------------------------
        # Validate Prediction Output
        # ---------------------------------------------

        if len(probabilities) != len(labels):

            raise RuntimeError(
                f"Model returned "
                f"{len(probabilities)} predictions, "
                f"but labels.json contains "
                f"{len(labels)} labels."
            )


        # ---------------------------------------------
        # Best Prediction
        # ---------------------------------------------

        predicted_index = int(
            np.argmax(probabilities)
        )


        confidence = float(
            probabilities[predicted_index]
            * 100
        )


        predicted_crop = labels[
            predicted_index
        ]


        # ---------------------------------------------
        # Top 3 Predictions
        # ---------------------------------------------

        top_count = min(
            3,
            len(probabilities),
        )


        top_indices = np.argsort(
            probabilities
        )[-top_count:][::-1]


        top_predictions = []


        for index in top_indices:

            index = int(index)

            top_predictions.append(
                {
                    "crop":
                        labels[index],

                    "confidence":
                        round(
                            float(
                                probabilities[index]
                                * 100
                            ),
                            2,
                        ),
                }
            )


        # ---------------------------------------------
        # Response
        # ---------------------------------------------

        return jsonify(
            {
                "success": True,

                "prediction":
                    {
                        "crop":
                            predicted_crop,

                        "confidence":
                            round(
                                confidence,
                                2,
                            ),
                    },

                "topPredictions":
                    top_predictions,

                "classes":
                    len(labels),
            }
        )


    except Exception as error:

        print(
            "Crop prediction error:",
            str(error),
        )


        return jsonify(
            {
                "success": False,

                "message":
                    "Failed to process crop image.",

                "error":
                    str(error),
            }
        ), 500


# =====================================================
# Start Server
# =====================================================

if __name__ == "__main__":

    print(
        "Starting Hawkins Farm Crop Recognition API..."
    )


    app.run(
        host="0.0.0.0",
        port=8000,
        debug=True,
    )